# Project information
site_name: ''
site_url: http://cardhub-br.github.io
site_author: cardhub-br
site_description: >-
  Explore todo o potencial do portal CardHub to Developers!

# Repository
repo_name: cardhub-br.github.io
repo_url: https://github.com/cardhub-br/cardhub-br.github.io/
edit_uri: edit/main/docs
edit_uri_template: 'blob/main/docs/{path}'

# Copyright
copyright: © 2023 Company - Todos os direitos reservados

# Page tree
nav:
        - Inicio: index.md
        - Guias:
                - Introdução: guia/introducao.md
                - Conhecendo o portal: guia/conhecendo.md
                - O que tem na API: guia/api-multi-produtos.md
                - Como ter minha credencial: guia/como-ter-minha-credencial.md
                - Glossário: guia/glossario.md
                - API de Vendas:
                        - Conciliação de vendas: guia/conciliacao-de-venda.md
                - Suporte:
                        - Suporte e Atendimento: guia/suporte-e-atendimento.md
                - Boas Práticas de Integração:
                        - Consultas: guia/boas-praticas.md
                        - Dependência entre transações de venda e pagamento: guia/conciliacoes.md
        - Referência da API: sobre.md
        - Registro de alterações: changelog.md
        - Discussões: comentarios.md
        - Suporte: suporte.md 

               
# Configuration
theme:
        name: material
        custom_dir: overrides
        language: pt-BR
        logo: assets/images/logo_cardhub_azul_horizontal.png
        favicon: assets/images/favicon-cardhub.png
        features:
                - announce.dismiss
                # - content.action.edit
                # - content.action.view
                - content.code.annotate
                - content.code.copy
                # - content.tabs.link
                - content.tooltips
                # - header.autohide
                - navigation.expand
                # - navigation.footer
                - navigation.indexes
                # - navigation.instant
                # - navigation.prune
                - navigation.sections
                - navigation.tabs
                - navigation.tabs.sticky
                - navigation.top
                - navigation.tracking
                - search.highlight
                - search.share
                - search.suggest
                - toc.follow
                # - toc.integrate
        palette:
                - scheme: default
                  primary: indigo
                  accent: indigo
                  toggle:
                    icon: material/brightness-7
                    name: Switch to dark mode
                - scheme: slate
                  primary: indigo
                  accent: indigo
                  toggle:
                    icon: material/brightness-4
                    name: Switch to light mode
        font:
                text: Roboto
                code: Roboto Mono


# Customization
extra:
        analytics:
                provider: google
                property: !ENV GOOGLE_ANALYTICS_KEY
        social:
                - icon: fontawesome/brands/instagram
                  link: https://www.instagram.com/grupocard_oficial/
                - icon: fontawesome/brands/youtube
                  link: https://www.youtube.com/channel/UCtBDr_BJXvlvwnni2Fz9VOg
                - icon: fontawesome/brands/linkedin
                  link: https://www.linkedin.com/company/grupocardoficial
                - icon: fontawesome/brands/facebook
                  link: https://www.facebook.com/grupocardoficial
                - icon: fontawesome/brands/github
                  link: https://github.com/cardhub-br
                  
        caption: true
        lazy_load: true
        align: center
        generator: false

# CSS e Javascript
extra_css:
    - 'assets/css/extra.css'
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - assets/javascripts/highlight.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - assets/javascripts/tablesort.js

# Plugins
plugins:
        - search:
                lang: pt
        - minify:
                minify_html: true
        - git-revision-date-localized:
                # enabled: !ENV [CI, false]
                enable_creation_date: true
                fallback_to_build_date: false
                type: timeago

# Extensions
markdown_extensions:
        - abbr
        - admonition
        - attr_list
        - def_list
        - footnotes
        - md_in_html
        #- toc:
        #        permalink: true
        - pymdownx.arithmatex:
                generic: true
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.details
        - pymdownx.emoji:
                emoji_generator: !!python/name:materialx.emoji.to_svg
                emoji_index: !!python/name:materialx.emoji.twemoji
        - pymdownx.highlight:
                anchor_linenums: true
                line_spans: __span
                pygments_lang_class: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.keys
        - pymdownx.magiclink:
                repo_url_shorthand: true
                user: cardhub-br
                repo: cardhub-br.github.io
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
                custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.tabbed:
                alternate_style: true
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tilde
        
